# Generated by Django 5.2.5 on 2026-04-10 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_legacy_admin_role(apps, schema_editor):
    """Old signups could set role='admin'. Admins are now superusers only."""
    User = apps.get_model("core", "User")
    User.objects.filter(role="admin").update(role="user")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_admin_role, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
