# Generated by Django 5.2.5 on 2025-11-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subcategory_status_user_is_blocked'),
        ('core', '0003_subcategory_status'),
    ]

    operations = [
    ]
