# Generated by Django 5.2.8 on 2025-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
