# Generated by Django 5.2.5 on 2025-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
