# Generated by Django 5.2.5 on 2025-11-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_is_featured'),
        ('seller', '0003_sellerdetails_is_blocked'),
    ]

    operations = [
    ]
